<template>
	<section>
		<h2>Privacy Policy</h2>
		<p>This is the web site of Organization Research and Development Associates.</p>
		<p>Our e-mail address is: <a href="mailto:webmaster@orda-us.com">webmaster@orda-us.com</a></p>
		<p>As corporate culture measurement and management business consultants, Organization Research and Development Associates takes the issue of privacy very seriously. We are therefore very sensitive to any concerns regarding our website use. We have very strict firewall and security measures, as well as company policies in place to protect users visiting our website.</p>
		<p>We do not sell, rent, or in any other way disclose information collected on this website. This includes any and all information you may provide, such as your name, company name, industry, email addresses, etc.</p>
		<p>Like all commercial websites, Organization Research and Development Associates collects and records some information about each visit to our site. For each user, the information we collect includes, but is not limited to, the domain name, pages and information viewed, IP addresses, and actions taken. This non-personal information is used to identify how you, the user, uses our website and where you may be located geographically. Further, the information we collect is used to improve our content, contact users for replies to requests of services or information, and for sales and marketing purposes.</p>
		<p>Organization Research and Development Associates collects the e-mail addresses of those who contact us directly through the website, volunteers information (such as survey information requests and/or user registrations), and of users requesting information or to be contacted directly by our associates. If you do not wish to receive e-mails from us, please send us an e-mail to the address listed above or contact us directly at the address, phone or fax numbers listed above.</p>
		<p>Those users providing us with a postal address and/or their telephone number(s) may be contacted by us with information requested on-line. They may also be contacted regarding information on new services, new products, or future events. If you do not wish to receive future contact from us, please let us know by sending an e-mail to the address listed above or by contacting us directly at the address, phone or fax numbers listed above.</p>
		<p>Our website may contain links to other websites that are owned and operated by third parties. These sites may have privacy and security policies that are different from Organization Research and Development Associates. Organization Research and Development Associates has no control over these sites, their use, and is not responsible for the practices and/or policies followed by these third parties. The Organization Research and Development Associates privacy policy applies only to information gathered by this website.</p>
		<p>If you feel that Organization Research and Development Associates has in any way not followed this privacy policy and you wish to issue a complaint, please <a href="mailto:webmaster@orda-us.com">contact us</a></p>
	</section>
</template>
