<template>
	<section>
		<h2>Terms of Use</h2>
		<p>Notice to users:</p>
		<p>Your access and use of this website means you are agreeing to and subject to the following terms and conditions and all applicable laws and regulations in the United States, all of which are subject to change at any time without prior notice. By accessing and using this website, you accept the following terms and conditions, without limitation or qualification: The trademarks appearing on this website, whether they are registered or unregistered, are the property of Organization Research and Development Associates. These trademarks may not be used without the written permission of Organization Research and Development Associates or the identified owner(s) of these trademarks. Unless otherwise pointed out or recognized, the copyright in the content of this website is owned by Organization Research and Development Associates.</p>
		<p>Reproduction, in any form, of any content of this website, without prior written authorization from Organization Research and Development Associates, is strictly prohibited. This website and the content provided within this site, including but not limited to, written text, script, images, graphics, audio, video, buttons, html code, and surveys may not be copied, reproduced, posted, uploaded, distributed, transmitted, or republished in any way, without the prior written consent of Organization Research and Development Associates.</p>
		<p>All information provided on this website is for informational purposes only and is free of charge. Further, all information provided on this website is general in nature and is not intended to address the circumstances of any particular individual or company. No one should act upon any information from this website content without appropriate professional advice and only after a thorough examination of the facts of the particular situation. No implied or other license is made regarding the content of this website. The information and material on this site is provided only for general instructional and/or illustrative purposes. It does not create a business, contractual, employment, or professional consulting services relationship of any kind.</p>
		<p>In no event shall Organization Research and Development Associates or any of its employees or contractors be liable for any damages whatsoever in connection with the information or material on this web site, including but not limited to actual, direct, incidental, indirect, consequential, exemplary, punitive or special damages.</p>
		<p>If you, the user, have any questions or comments regarding Organization Research and Development Associates, our consulting services, it’s website, or would like to obtain permission to use any of the information or content in Organization Research and Development Associates website, please contact Organization Research and Development Associates at www.orda-us.com.</p>
	</section>
</template>
